on: push

jobs:
  ps7-test-module:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh # ps7 core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pester Test
        run: |
          $config = New-PesterConfiguration
          $config.CodeCoverage.Enabled = $true
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config

      - name: Upload code coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml

  ps5-test-module:
    defaults:
      run:
        shell: powershell # ps5 (windows only)

    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pester Test
        run: |
          $config = New-PesterConfiguration
          $config.CodeCoverage.Enabled = $true
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config

      - name: Upload code coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.xml
